import Button from "../../lib/components/Button/Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/fHb0XUhWXZErq97C6N9uG3/-BETA--Dashboard-Design-System?node-id=3910%3A12",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      subType: figma.enum("subType", {
        link: "link",
        default: "default",
        iconOnly: "iconOnly",
      }),
      text: figma.string("text"),
      disabled: figma.enum("state", {
        disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "hasLeftIcon": figma.boolean('hasLeftIcon'),
      // "hasRightIcon": figma.boolean('hasRightIcon'),
      // "rightIcon": figma.instance('rightIcon'),
      // "leftIcon": figma.instance('leftIcon'),
      // "text": figma.string('text'),
      // "type": figma.enum('type', {
      //   "primary": "primary",
      //   "secondary": "secondary",
      //   "danger": "danger",
      //   "success": "success"
      // })
    },
    example: (props) => (
      <Button
        size={props.size}
        subType={props.subType}
        text={props.text}
        disabled={props.disabled}
      />
    ),
  },
)
