import SplitTag from "../../lib/components/Tag/SplitTag"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SplitTag,
  "https://www.figma.com/design/fHb0XUhWXZErq97C6N9uG3/-BETA--Dashboard-Design-System?node-id=5864%3A8098",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      color: figma.enum("color", {
        neutral: "neutral",
        primary: "primary",
        success: "success",
        error: "error",
        warning: "warning",
        purple: "purple",
      }),
      // No matching props could be found for these Figma properties:
      // "variant": figma.enum('variant', {
      //   "splitTags": "splittags"
      // }),
      // "style": figma.enum('style', {
      //   "rounded": "rounded",
      //   "squarical": "squarical"
      // })
    },
    example: (props) => <SplitTag size={props.size} color={props.color} />,
  },
)
