import Tag from "../../lib/components/Tag/Tag"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/fHb0XUhWXZErq97C6N9uG3/-BETA--Dashboard-Design-System?node-id=2021%3A8332",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("variant", {
        noFill: "noFill",
        attentive: "attentive",
        subtle: "subtle",
      }),
      size: figma.enum("size", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
      }),
      color: figma.enum("color", {
        neutral: "neutral",
        primary: "primary",
        success: "success",
        error: "error",
        warning: "warning",
        purple: "purple",
      }),
      // No matching props could be found for these Figma properties:
      // "slot1": figma.instance('Slot 1'),
      // "hasslot1": figma.boolean('has_slot_1'),
      // "slot2": figma.instance('Slot 2'),
      // "hasslot2": figma.boolean('has_slot_2'),
      // "hasLabel": figma.boolean('hasLabel'),
      // "text": figma.string('text'),
      // "style": figma.enum('style', {
      //   "squarical": "squarical",
      //   "rounded": "rounded"
      // })
    },
    example: (props) => (
      <Tag variant={props.variant} size={props.size} color={props.color} />
    ),
  },
)
