import Tooltip from "../../lib/components/Tooltip/Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/fHb0XUhWXZErq97C6N9uG3/-BETA--Dashboard-Design-System?node-id=3650%3A871",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("size", {
        sm: "sm",
        lg: "lg",
      }),
      arrow: figma.enum("arrow", {
        none: "none",
        right: "right",
        left: "left",
        bottomCenter: "bottomCenter",
        bottomLeft: "bottomLeft",
        bottomRight: "bottomRight",
        topCenter: "topCenter",
        topLeft: "topLeft",
        topRight: "topRight",
      }),
      slotDirection: figma.enum("slotDirection", {
        right: "right",
        left: "left",
      }),
      slot: figma.enum("slotDirection", {
        right: "g",
      }),
      // No matching props could be found for these Figma properties:
      // "hasSlot": figma.boolean('hasSlot'),
      // "slot": figma.instance('slot')
    },
    example: (props) => (
      <Tooltip
        content="Tooltip content"
        size={props.size}
        arrow={props.arrow}
        slotDirection={props.slotDirection}
        slot={props.slot}
      >
        <button>Hover me</button>
      </Tooltip>
    ),
  },
)
